functions:
    logger:
        path: /home/$USER/print_position_logger/logger.py
        function: increment_number
    unlog:
        path: /home/$USER/print_position_logger/logger.py
        function: clear_file
