functions:
    logger:
        path: /home/$USER/Klipper_Power_Resume/logger.py
        function: increment_number
    unlog:
        path: /home/$USER/Klipper_Power_Resume/logger.py
        function: clear_file
